### ISSUE TITLE
Extend Configurations

### ISSUE THREAD

**Issue by ctate** [ctate/autocode#4]
Add ability to extend configurations to other modules:

``` yaml
imports:
  crystal/license: ~0.2.4
outputs:
  - generator: license.MITGenerator
    spec:
      copyright: 2015 Crystal
```

``` yaml
extends:
  crystal/config: ~0.1.0
```
